### ISSUE TITLE
Wrong url in Google Analytics

### ISSUE THREAD

**Issue by gerben86** [fooman/googleanalyticsplus-implementation-m2#1]
I found this JSON in the page:

```
{
    "*": {
        "Magento_GoogleAnalytics/js/google-analytics": {
            "isCookieRestrictionModeEnabled": 0,
            "currentWebsite": 1,
            "cookieName": "user_allowed_save_cookie",
            "ordersTrackingData": [],
            "pageTrackingData": {"optPageUrl":"\/catalog\/product\/view\/id\/2","isAnonymizedIpActive":false,"accountId":"UA-11111-1","isDisplayFeaturesActive":0,"isEnhancedLinksActive":1}        }
    }
}
```
As you can see the catalog/product/view/id/2 isn't desired.
This can be fixed by replacing `getPathInfo()` with `getRequestUri()` in `src\Helper\Url.php`

I'm using Magento 2.3.4 and "fooman/googleanalyticsplus-m2": "^4.0",

**Comment by fooman** [comment]
@gerben86 Thanks for the report. I have added the above functionality, however as this would be messing with existing implementations I have decided to make this configurable. The setting to enable it is "Use Path Info as Tracked Url".
